apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aurora-pm
  namespace: aurora-pm
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: aurora-pm.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aurora-pm-web
                port:
                  number: 3000
    - host: api.aurora-pm.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aurora-pm-api
                port:
                  number: 8080
